### ISSUE TITLE
send_string in master giving error

### ISSUE THREAD

**Issue by pullenrc** [KMKfw/kmk_firmware#206]
When using send_string to send 'int' this happend:
`Traceback (most recent call last):
      File "main.py", line 50, in <module>
      File "kmk/handlers/sequences.py", line 45, in send_string
KeyError: t`

offending line in main:
`INT = send_string('int')`

This works fine in the current main branch, portingmy files over to the rebased branch is when I am having the errors

**Comment by pullenrc** [comment]
From what I am looking at, when send_string is called, the KC dict is empty.
Iget this in MU:
`Traceback (most recent call last):
  File "main.py", line 45, in <module>
  File "kmk/handlers/sequences.py", line 44, in send_string
KeyError: h`

When  I try to print the KC like this:
`def send_string(message):
    seq = []
    print('KC : {}'.format(KC))
    for char in message:
        kc = KC[char]
        if char.isupper():
            kc = KC.LSHIFT(kc)

        seq.append(kc)

    return simple_key_sequence(seq)`

I get:
`main.py output:
KC : {}
Traceback (most recent call last):
  File "main.py", line 45, in <module>
  File "kmk/handlers/sequences.py", line 45, in send_string
KeyError: h`
