### ISSUE TITLE
Firmware Hang Up at using ModTap on a split keyboard

### ISSUE THREAD

**Issue by yoichiro** [KMKfw/kmk_firmware#256]
I'm a keyboard designer of the Lunakey Pico which is a split keyboard. When tapping a key with the ModTap setting on the right side which the USB cable is not connected, the firmware on the right side is hanged up.

For example, I set the following ModTap keycode on the right side (that is, I use the [main.py](https://github.com/KMKfw/kmk_firmware/blob/master/boards/lunakey_pico/main.py) ):

```
KC.MT(KC.MINS, KC.LSHIFT)
```

Then, when tapping the key, the `-` character is sent, but at the same time, the following error occurs:

```
Traceback (most recent call last):
  File "main.py", line 120, in <module>
  File "kmk/kmk_keyboard.py", line 497, in go
  File "kmk/kmk_keyboard.py", line 115, in _send_hid
  File "kmk/hid.py", line 128, in send
  File "kmk/hid.py", line 233, in hid_send
OSError: USB busy
```

I seems that the firmware tried sending hid report at tapping the key set as ModTap on the right side. However, the USB cable is not connected on the right side. Instead, the TRRS cable is connected on the right side to communicate with the  left side using an UART.

The photo of the Lunakey Pico is below:

![PXL_20211015_061214796](https://user-images.githubusercontent.com/261787/137440720-24b2097c-2737-4fad-b863-c6e82c170675.jpg)

In my keyboard, this issue occurs 100% on the right side. But, this issue never occur on the left side because the USB connection established.

**Comment by yoichiro** [comment]
Feel free to let me know if you want to add a code for debug. I can try it in my keyboard.
