### ISSUE TITLE
Bug on Split keyboards (mirror or left only for both sides)

### ISSUE THREAD

**Issue by ldsands** [KMKfw/kmk_firmware#406]
So after the OneShot keys were fixed (thanks by the way). I updated everything and found that my halves are now only will use the left half of the keymap. I have tried several different variations/combinations of using the split options below. No combinations of these variables allows the right half to be the right half. I did rename the usb storage to `SOFLEV2L` and `SOFLEV2R` I have not removed the L and R because I cannot figure out an easy way to do it (I recently switched to Linux full time). So the EE hands feature might be involved with this somehow.

```python
target_left=True, 
split_side=SplitSide.LEFT,
split_flip=True,
```

If I had to guess it was probably the changes made to `split.py` [here](https://github.com/KMKfw/kmk_firmware/pull/402/files#diff-60be404174a94d655cb4beae62a821cc693dcab6f99b55da3917c129412b5ce0) or [here](https://github.com/KMKfw/kmk_firmware/commit/7431192e95bc2a1a0d23cdab076187ec4d9cfc23) that messed it up. I can confirm that it works fine as of the commit made on Apr 5th (7b92596). I've tried to figure out what caused it but I havn't made any progress.

I'll post my `kb.py` and `main.py` code below.

Any help would be appreciated.

PS

I don't think this is as useful but just in case. Whenever a key is simultaneously pressed at the same time as another key on the other side, this is the error that occurs.

```python
KeyNotPressed(ic=13)
Traceback (most recent call last):
  File "main.py", line 120, in <module>
  File "kmk/kmk_keyboard.py", line 422, in go
  File "kmk/kmk_keyboard.py", line 476, in _main_loop
  File "kmk/kmk_keyboard.py", line 116, in _handle_matrix_report
  File "kmk/kmk_keyboard.py", line 179, in _on_matrix_changed
KeyError: 13
```

**Comment by ldsands** [comment]
<details>
    <summary>`kb.py`</summary>

    ```python
    import board

    from kmk.kmk_keyboard import KMKKeyboard as _KMKKeyboard
    from kmk.scanners import DiodeOrientation


    class KMKKeyboard(_KMKKeyboard):
        col_pins = (board.A1, board.A0, board.SCK, board.MISO, board.MOSI, board.D21)
        row_pins = (board.D5, board.D6, board.D7, board.D8, board.D9)
        diode_orientation = DiodeOrientation.COL2ROW
        encoder_pin_0 = board.A2
        encoder_pin_1 = board.A3
        # i2c = board.I2C
        coord_mapping = [
        0,  1,  2,  3,  4,  5,    35, 34, 33, 32, 31, 30,
        6,  7,  8,  9, 10, 11,    41, 40, 39, 38, 37, 36,
        12, 13, 14, 15, 16, 17,    47, 46, 45, 44, 43, 42,
        18, 19, 20, 21, 22, 23,    53, 52, 51, 50, 49, 48,
        24, 25, 26, 27, 28, 29,    59, 58, 57, 56, 55, 54
        ]
    ```

</details>

<details>
    <summary>`main.py`</summary>

    ```python
    # version 3.0.0

    import board

    from kb import KMKKeyboard
    from kmk.keys import KC
    from kmk.modules.encoder import EncoderHandler
    from kmk.modules.layers import Layers
    from kmk.modules.oneshot import OneShot
    from kmk.modules.split import Split, SplitSide, SplitType

    keyboard = KMKKeyboard()
    # load modules
    layers_ext = Layers()
    oneshot = OneShot()
    encoder_handler = EncoderHandler()
    split = Split(
        split_flip=True,  # If both halves are the same, but flipped, set this True
        data_pin=board.RX,  # The primary data pin to talk to the secondary device with
        data_pin2=board.TX,  # Second uart pin to allow 2 way communication
        use_pio=True,  # allows for UART to be used with PIO
        # target_left=True,  # Assumes that left will be the one on USB. Set to false if using the right
        # split_side=SplitSide.LEFT,  # Sets if this is to SplitSide.LEFT or SplitSide.RIGHT, or use EE hands
        # split_side=SplitSide.RIGHT,  # Sets if this is to SplitSide.LEFT or SplitSide.RIGHT, or use EE hands
    )
    keyboard.modules = [layers_ext, split, oneshot, encoder_handler]

    # Layers
    # Layer 0 WORKMAN
    MO_WORK = KC.MO(0)
    TO_WORK = KC.TO(0)
    # Layer 1 FUNCTION
    MO_FUNCT = KC.MO(1)
    TO_FUNCT = KC.TO(1)
    # Layer 2 NUMBER
    MO_NUM = KC.MO(2)
    TO_NUM = KC.MO(2)
    # Layer 3 NAVITATION
    MO_NAV = KC.MO(3)
    TO_NAV = KC.TO(3)
    # Layer 4 QWERTY
    MO_QWER = KC.MO(4)
    TO_QWER = KC.TO(4)
    # Cleaner key names
    XXXXXXX = KC.NO
    # OneShot Keys, tap_time is tap timeout in ms (default: 1000ms)
    OS_LCTL = KC.OS(KC.LCTL, tap_time=None)
    OS_LSFT = KC.OS(KC.LSFT, tap_time=None)
    OS_LGUI = KC.OS(KC.LGUI, tap_time=None)
    OS_LALT = KC.OS(KC.LALT, tap_time=None)
    # Combo Keys
    UNDO = KC.LCTL(KC.Z)
    CUT = KC.LCTL(KC.X)
    COPY = KC.LCTL(KC.C)
    PASTE = KC.LCTL(KC.V)
    LSTRT = KC.LCTL(KC.HOME)
    LEND = KC.LCTL(KC.END)
    BACK = KC.LALT(KC.LEFT)
    NEXT = KC.LALT(KC.RGHT)
    LBSPC = KC.LCTL(KC.BSPC)
    CTTAB = KC.LCTL(KC.TAB)
    ALTTAB = KC.LALT(KC.TAB)
    SHALTAB = KC.LALT(KC.LSFT(KC.TAB))

    keyboard.keymap = [
        [  # WORKMAN
            #HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#ENCODER--#ENCODER--#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----
            KC.ESC,   KC.N1,    KC.N2,    KC.N3,    KC.N4,    KC.N5,                                            KC.N6,    KC.N7,    KC.N8,    KC.N9,    KC.N0,    KC.MINS,
            KC.LPRN,  KC.Q,     KC.D,     KC.R,     KC.W,     KC.B,                                             KC.J,     KC.F,     KC.U,     KC.P,     KC.SCLN,  KC.PIPE,
            KC.RPRN,  KC.A,     KC.S,     KC.H,     KC.T,     KC.G,                                             KC.Y,     KC.N,     KC.E,     KC.O,     KC.I,     KC.QUOT,
            OS_LALT,  KC.Z,     KC.X,     KC.M,     KC.C,     KC.V,                                             KC.K,     KC.L,     KC.COMM,  KC.DOT,   KC.SLSH,  KC.ENT,
                                OS_LGUI,  MO_FUNCT, OS_LSFT,  KC.SPC,   OS_LCTL,  TO_NAV,   TO_WORK,  KC.DEL,   KC.BSPC,  MO_NUM,   CTTAB,    KC.TAB,
        ],
        [  # FUNCTION
            #HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#ENCODER--#ENCODER--#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----
            XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                                          XXXXXXX,  KC.LCBR,  KC.PLUS,  KC.RCBR,  XXXXXXX,  XXXXXXX,
            XXXXXXX,  XXXXXXX,  XXXXXXX,  KC.VOLD,  KC.VOLU,  XXXXXXX,                                          KC.PGUP,  KC.HOME,  KC.UP,    KC.END,   XXXXXXX,  XXXXXXX,
            XXXXXXX,  XXXXXXX,  XXXXXXX,  KC.MPLY,  KC.MUTE,  XXXXXXX,                                          LBSPC,    KC.LEFT,  KC.DOWN,  KC.RGHT,  XXXXXXX,  XXXXXXX,
            KC.LALT,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                                          KC.PGDN,  KC.LBRC,  KC.EQL,   KC.RBRC,  XXXXXXX,  XXXXXXX,
                                KC.LGUI,  XXXXXXX,  KC.LSFT,  KC.SPC,   KC.LCTL,  TO_NAV,   TO_WORK,  KC.SPC,   XXXXXXX,  KC.LPRN,  KC.GRV,   KC.RPRN,
        ],
        [  # NUMBER
            #HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#ENCODER--#ENCODER--#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----
            KC.F1,    KC.F2,    KC.F3,    KC.F4,    KC.F5,    KC.F6,                                            XXXXXXX,  KC.NLCK,  KC.PSLS,  KC.PAST,  KC.PMNS,  KC.BSPC,
            KC.F7,    KC.F8,    KC.F9,    KC.F10,   KC.F11,   KC.F12,                                           XXXXXXX,  KC.N7,    KC.N8,    KC.N9,    KC.PPLS,  KC.DEL,
            XXXXXXX,  XXXXXXX,  XXXXXXX,  SHALTAB,  ALTTAB,   XXXXXXX,                                          XXXXXXX,  KC.N4,    KC.N5,    KC.N6,    KC.PCMM,  XXXXXXX,
            KC.LALT,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                                          KC.N0,    KC.N1,    KC.N2,    KC.N3,    KC.PEQL,  KC.ENT,
                                KC.LGUI,  XXXXXXX,  KC.LSFT,  XXXXXXX,  KC.LCTL,  TO_NAV,   TO_WORK,  KC.DEL,   KC.BSPC,  XXXXXXX,  XXXXXXX,  XXXXXXX,
        ],
        [  # NAVIGATION
            #HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#ENCODER--#ENCODER--#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----#HERE-----
            TO_WORK,  TO_FUNCT, TO_NUM,   TO_NAV,   TO_QWER,  XXXXXXX,                                          XXXXXXX,  KC.NLCK,  KC.PSLS,  KC.PAST,  KC.PMNS,  KC.BSPC,
            XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                                          XXXXXXX,  KC.KP_7,  KC.KP_8,  KC.KP_9,  KC.PPLS,  KC.DEL,
            XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                                          XXXXXXX,  KC.KP_4,  KC.KP_5,  KC.KP_6,  KC.PCMM,  XXXXXXX,
            KC.LALT,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,                                          KC.KP_0,  KC.KP_1,  KC.KP_2,  KC.KP_3,  KC.PEQL,  KC.ENT,
                                KC.LGUI,  XXXXXXX,  KC.LSFT,  XXXXXXX,  KC.LCTL,  TO_NAV,   TO_WORK,  XXXXXXX,  KC.BSPC,  XXXXXXX,  XXXXXXX,  XXXXXXX,
        ],
        [  # QWERTY
            # HERE----# HERE----# HERE----# HERE----# HERE----# HERE----# HERE----#ENCODER--#ENCODER--# HERE----# HERE----# HERE----# HERE----# HERE----# HERE----# HERE----
            KC.ESC,   KC.N1,    KC.N2,    KC.N3,    KC.N4,    KC.N5,                                            KC.N6,    KC.N7,    KC.N8,    KC.N9,    KC.N0,    KC.MINS,
            KC.TAB,   KC.Q,     KC.W,     KC.E,     KC.R,     KC.T,                                             KC.Y,     KC.U,     KC.I,     KC.O,     KC.P,     KC.PIPE,
            KC.GRV,   KC.A,     KC.S,     KC.D,     KC.F,     KC.G,                                             KC.H,     KC.J,     KC.K,     KC.L,     KC.SCLN,  KC.QUOT,
            KC.LALT,  KC.Z,     KC.X,     KC.C,     KC.V,     KC.B,                                             KC.N,     KC.M,     KC.COMM,  KC.DOT,   KC.SLSH,  KC.ENT,
                                KC.LGUI,  MO_FUNCT, KC.LSFT,  KC.SPC,   KC.LCTL,  TO_NAV,   TO_WORK,  KC.SPC,   KC.BSLS,  MO_NUM,   CTTAB,    KC.TAB,
        ]
    ]

    encoder_handler.pins = ((keyboard.encoder_pin_1, keyboard.encoder_pin_0, None, False),)
    encoder_handler.map = (
        ((KC.VOLD, KC.VOLU),),  # WORKMAN
        ((KC.VOLD, KC.VOLU),),  # FUNCTION
        ((KC.VOLD, KC.VOLU),),  # NUMBER
        ((KC.VOLD, KC.VOLU),),  # NAVIGATION
        ((KC.VOLD, KC.VOLU),),  # QWERTY
    )

    print("Keyboard Ready (Left)")

    if __name__ == "__main__":
        keyboard.go()

    ```

</details>
