### ISSUE TITLE
Latest master has corrupt file

### ISSUE THREAD

**Issue by SethSenpai** [KMKfw/kmk_firmware#560]
Hey there, 

Pretty new to python on embedded so maybe this is obvious. I've installed the latest master of KMK as instructed on my RPI Pico and tried the first example code which worked. When I added the rgb extension the device stopped working as a keyboard and the neopixel did not light up. Nor was there any data on the pin that I could see with my scope. 

Digging a bit deeper I enabled the debugging and connected to the serial device. Manually importing the RGB extension and trying to initialize the module I got the following error:

```
>>> from kmk.extensions.rgb import RGB
>>> rgb_e = RGB(pixel_pin=board.GP22, num_pixels=1, hue_default=190, sat_default=100, val_default=127)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kmk/extensions/rgb.py", line 111, in __init__
RuntimeError: Corrupt .mpy file
```

Any clue how to get around this?

**Comment by SethSenpai** [comment]
Located the problem. Turns out the neopixel.py that I added to my lib folder was corrupt. Cleared the storage and reuploaded the files. It works now.
